spring:
  application:
    name: smart-job
  datasource:
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/smart-job
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    redis:
      host: localhost
      port: 6379
      password:
  jpa:
    properties:
      show-sql: true
      #自动建表
      hibernate:
        hbm2ddl:
          auto: update
        dialect: org.hibernate.dialect.MySQL8Dialect
logging:
  level:
    com.fhxf: DEBUG
  file:
    path: "logs/${spring.application.name}"
server:
  port: 3000
  hikari:
    pool-name: HikariCPDatasource
    minimum-idle: 5
    idle-timeout: 180000
    maximum-pool-size: 10
    auto-commit: true
    max-lifetime: 1800000
    connection-timeout: 30000
    connection-test-query: SELECT 1
    redis:
      database: 0
      host: 127.0.0.1
      port: 6379
      jedis:
        pool:
          max-active: 20
          max-wait: -1
          max-idle: 10
          min-idle: 0
      timeout: 2000
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
smart-job:
  jwt:
    location: classpath:hmall.jks
    alias: hmall
    password: hmall123
    tokenTTL: 30m
  auth:
    excludePaths:
      - /search/**
      - /auth/login
      - /auth/logout
      - /auth/autoLogin
      - /auth/enterpriseRegister
      - /auth/workerRegister
      - /auth/captcha
      - /auth/verifyCaptcha
      - /items/**
      - /file/**
      - /hi
project:
  folder: F:\java\项目\smart-job\backend\file
ffmpeg:
  showLog: true
